name: hw33
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.2

  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.7
  provider: ^6.1.2

  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.4
  firebase_storage: ^12.4.4

  firebase_messaging: ^15.2.4

  sqflite: ^2.0.3
  path_provider: ^2.0.11
  http: ^1.3.0
  path: ^1.8.3
  mockito: ^5.4.5
  build_runner: ^2.4.14
  intl: ^0.20.2

  # Firebase dependencies

  cloud_firestore: ^5.6.5

  # QR Code package
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash.gif
