// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCTP1I6WUyKQ9Wsa31ewwONC3-ABCrOcI',
    appId: '1:20933973525:web:10e227e8823b17b7aa601c',
    messagingSenderId: '20933973525',
    projectId: 'workout-app-93b4c',
    authDomain: 'workout-app-93b4c.firebaseapp.com',
    storageBucket: 'workout-app-93b4c.firebasestorage.app',
    measurementId: 'G-W0HMQRZ1VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgNx5kzHk0mnvnNXIp-594MLYntnd3Epk',
    appId: '1:20933973525:android:72444f7dc4be372eaa601c',
    messagingSenderId: '20933973525',
    projectId: 'workout-app-93b4c',
    storageBucket: 'workout-app-93b4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2LF4wTlHqdHPyZiPyK46fYSpKzbSC_xI',
    appId: '1:20933973525:ios:c5395095c8932b8faa601c',
    messagingSenderId: '20933973525',
    projectId: 'workout-app-93b4c',
    storageBucket: 'workout-app-93b4c.firebasestorage.app',
    iosBundleId: 'com.example.hw33',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2LF4wTlHqdHPyZiPyK46fYSpKzbSC_xI',
    appId: '1:20933973525:ios:c5395095c8932b8faa601c',
    messagingSenderId: '20933973525',
    projectId: 'workout-app-93b4c',
    storageBucket: 'workout-app-93b4c.firebasestorage.app',
    iosBundleId: 'com.example.hw33',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCTP1I6WUyKQ9Wsa31ewwONC3-ABCrOcI',
    appId: '1:20933973525:web:19cfb57851705906aa601c',
    messagingSenderId: '20933973525',
    projectId: 'workout-app-93b4c',
    authDomain: 'workout-app-93b4c.firebaseapp.com',
    storageBucket: 'workout-app-93b4c.firebasestorage.app',
    measurementId: 'G-8HCZFXWB2C',
  );
}
